spring.ldap.urls=ldaps://ipa00.thumbtack.lo
spring.ldap.anonymous-read-only=true



## PostgresSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=Rfhtkjd123
spring.jpa.hibernate.ddl-auto=create-drop
### logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true